### ISSUE TITLE
Optimizing suggestion

### ISSUE THREAD

**Issue by MilesChou** [rc1021/docker_with_laravel_53#5]
1. You should copy `composer.json` and `composer.lock` for execute `composer install`, and copy project file later. Like [Nodejs](https://git.io/vimsp)
2. Use `.dockerignore` and more fast on initializing build when you have a large repo. e.g. `vendor` folder is generated on build so that it can be ignore.

**Comment by Easter1021** [comment]
Hi @MilesChou , thank you for your suggestions.

I did the suggestion 2.

For suggestion 1, [ONBUILD](https://docs.docker.com/engine/reference/builder/#/onbuild) is nice  as a trigger, but I don't want to create `onbuild-image` for this repo. Why did you recommend that?

**Comment by MilesChou** [comment]
No, I don't mean using ONBUILD, but you can copy `composer.json` and `composer.lock` without ONBULID. Here is a example (remember add `vendor` into `.dockerignore`):

```dockerfile
FROM php:7.0-apache

# Install composer packages
COPY composer.json ./
COPY composer.lock ./
RUN composer install --profile --no-dev --optimize-autoloader

# Copy project files
COPY . ./
```

This has the benefit: Unless you change composer.json / composer.lock, otherwise it will not be executed composer install. In other words, it run composer install that only you change the composer dependency. You do the same, doesn't it?

On the contrary, the original Dockerfile executing composer install every time when you change source code.
